In [1]:
#NUMPY - Numerical Calculations (Numerical Python)
#MatPlotlib - Data Visualization
#Pandas - Data Analysis
#Seaborn - Advanced Data Visualization
#Sklearn - Machine Learning Algorithm
#opencv - Image Processing

In [2]:
import numpy as np

In [3]:
#arrays

In [4]:
list1 = [5,6,4,8,3]
list1

[5, 6, 4, 8, 3]

In [5]:
arr1 = np.array([5,6,4,8,3])
arr1

array([5, 6, 4, 8, 3])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
#why arrays when we have lists
#1 Python is very slow
#2 numpy is faster as it is written in C,C++
#3 numpy has a lot of functions to perform numerical calculations

In [8]:
len(arr1)

5

In [9]:
arr1[0]

5

In [10]:
arr1[1:3]

array([6, 4])

In [11]:
#Attributes of numpy array
#1 ndim
#2 size
#3 shape

In [12]:
arr1.ndim

1

In [13]:
arr1.size

5

In [14]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.size

8

In [18]:
arr2.shape

(2, 4)

In [19]:
arr2.reshape(4,2) #reshape as long as size remains same

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
arr2.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [21]:
arr2.reshape(8) #single dimesional array using reshape

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
arr2.reshape(2,4,1) #3D array using reshape

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [23]:
arr3 = arr2.reshape(2,2,2)

In [24]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr3.ndim

3

In [26]:
arr3.shape

(2, 2, 2)

In [27]:
arr3.size

8

In [28]:
#WHY IS NUMPY FASTER
#numpy stores data as 32bits compared to lots of data for int type 
#numpy uses contiguous memory

In [29]:
#APPLICATIONS
#Mathematics - matlab replacement
#Plotting - matplotlib
#Backend - pandas
#Machine Learning

In [30]:
import numpy as np

In [31]:
a = np.array([1,2,3,4])

In [32]:
a

array([1, 2, 3, 4])

In [33]:
print(a)

[1 2 3 4]


In [34]:
b = np.array([[9.0,8.0,7.0],[1.0,2.0,4.0]])

In [35]:
print(b)

[[9. 8. 7.]
 [1. 2. 4.]]


In [36]:
#Get Dimensions , shape

In [37]:
a.ndim

1

In [38]:
a.shape

(4,)

In [39]:
b.ndim

2

In [40]:
b.shape

(2, 3)

In [41]:
#Type and size

In [42]:
a.dtype

dtype('int32')

In [43]:
c = np.array([1,2,3,4],dtype='int16')

In [44]:
c.dtype

dtype('int16')

In [45]:
c.itemsize

2

In [46]:
a.itemsize #size

4

In [47]:
a.size #no of items

4

In [48]:
a.size * a.itemsize

16

In [49]:
#total Size
a.nbytes

16

In [50]:
b.itemsize #float

8

In [51]:
b.nbytes

48

### ACCESSING/CHANGING SPECIFIC ELEMENTS,ROWS,COLUMNS

In [52]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [53]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [54]:
a.shape

(2, 7)

In [55]:
#get specific element

In [56]:
a[1,5]

13

In [57]:
a[1,-2]

13

In [58]:
#Get specific row

In [59]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
#Get specific columns

In [61]:
a[:,2]

array([ 3, 10])

In [62]:
#[startindex:endindex:stepsize]

In [63]:
a[0,1:6:2]

array([2, 4, 6])

In [64]:
a[0,1:-1:2]

array([2, 4, 6])

In [65]:
a[1,5] = 20

In [66]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [67]:
a[:,2] = 5

In [68]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [69]:
a[:,2] = [1,2]

In [70]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [71]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
#Get specific so use outside to in approach 
#for 4 we need 0,1,1
b[0,1,1]

4

In [73]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [74]:
b[:,1,:] = [[9,9],[8,8]]

In [75]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### Initializing Different Types of Arrays

In [76]:
# All 0s matrix

In [77]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [79]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [80]:
np.ones((4,2),dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [81]:
#Any other number
np.full((2,2),99,dtype='float32') #shape,number,dtype(optional)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [82]:
#any other number (full_like)
#make use if shape of other array that is previously defined

In [83]:
np.full_like(a,4) #same shape as a

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [84]:
# Random decimal numbers

In [85]:
np.random.rand(4,2)

array([[0.20027501, 0.0790896 ],
       [0.97389215, 0.89650966],
       [0.37468817, 0.57488739],
       [0.61323864, 0.74218961]])

In [86]:
np.random.rand(4,2,3)

array([[[0.42417317, 0.57412003, 0.20389834],
        [0.78857928, 0.36423204, 0.15598076]],

       [[0.0415529 , 0.19634121, 0.7528142 ],
        [0.66294082, 0.93897787, 0.11650077]],

       [[0.16335579, 0.47635922, 0.11126144],
        [0.25183676, 0.96738745, 0.6293629 ]],

       [[0.66763595, 0.69842183, 0.18535446],
        [0.78287553, 0.76465973, 0.69593812]]])

In [87]:
#if we want to use shaoe of other initialized array
np.random.random_sample(a.shape)

array([[0.35375933, 0.10614378, 0.4529119 , 0.4657758 , 0.48359221,
        0.20620467, 0.15826706],
       [0.35387745, 0.94549307, 0.68889055, 0.98058157, 0.16348446,
        0.90264194, 0.76360655]])

In [88]:
a.shape

(2, 7)

In [89]:
#random integers
np.random.randint(7)

6

In [90]:
#if we want a specific size

In [91]:
np.random.randint(7,size=(3,3))

array([[1, 0, 3],
       [0, 6, 2],
       [0, 2, 2]])

In [92]:
np.random.randint(-4,7,size=(3,3))

array([[-2, -3,  6],
       [ 5,  5,  6],
       [ 2,  0,  6]])

In [93]:
#identity matrix

In [94]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [95]:
#repeat an arrays

In [96]:
arr = np.array([1,2,3])

In [97]:
r1=np.repeat(arr,3,axis=0)

In [98]:
print(r1)

[1 1 1 2 2 2 3 3 3]


In [99]:
arr = [[1,2,3]]

In [100]:
r2 = np.repeat(arr,3,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [101]:
r2 = np.repeat(arr,3,axis=1)

In [102]:
print(r2)

[[1 1 1 2 2 2 3 3 3]]


### Challenge

In [103]:
a = np.ones(5)

In [104]:
a

array([1., 1., 1., 1., 1.])

In [105]:
a = np.ones((5,5),dtype='int32')

In [106]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [107]:
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [108]:
a[1:4,1:4] = 0

In [109]:
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [110]:
a[2,2]=9

In [111]:
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays!!!

In [112]:
a = np.array([1,2,3])

In [113]:
a

array([1, 2, 3])

In [114]:
b = a

In [115]:
b

array([1, 2, 3])

In [116]:
b[0] = 100

In [117]:
print(b)

[100   2   3]


In [118]:
print(a)

[100   2   3]


In [119]:
#b points to same thing as a so we actually didnt make a copy
#use copy() function

In [120]:
b = a.copy()

In [121]:
b[1] = 200

In [122]:
print(b)
print(a)

[100 200   3]
[100   2   3]


### MATHEMATICS

In [123]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [124]:
a+2

array([3, 4, 5, 6])

In [125]:
a-2

array([-1,  0,  1,  2])

In [126]:
a*2

array([2, 4, 6, 8])

In [127]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [128]:
a+=2
print(a)

[3 4 5 6]


In [129]:
b = np.array([1,0,1,0])

In [130]:
a+b

array([4, 4, 6, 6])

In [131]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [132]:
#take trig of all values

In [133]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [134]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

### Linear Algebra

In [135]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [136]:
#multiply matrices - if compatible
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [137]:
#Find the determinent
c = np.identity(3)
np.linalg.det(c)

1.0

In [138]:
#Similarly many other stuff like inverse , eigen values  etc

## REFERENCES

#Array Creation Routines - https://numpy.org/doc/stable/reference/routines.array-creation.html
#Mathematical Functions - https://numpy.org/doc/stable/reference/routines.math.html
#Linear Algebra - 
https://numpy.org/doc/stable/reference/routines.linalg.html

### Statistics

In [139]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.min(stats)

1

In [141]:
np.max(stats)

6

In [142]:
np.min(stats,axis=1) #axis = 1 gives row wise 0 gives columns wise

array([1, 4])

In [143]:
np.max(stats,axis=1)

array([3, 6])

In [144]:
np.sum(stats)

21

### Reorganizing arrays

In [145]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [146]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [147]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [148]:
after = before.reshape((4,2))
print(after)
after = before.reshape((2,2,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [149]:
#Vertically stacking arrays

In [150]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [151]:
#horizontal stack

In [152]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [153]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

Load Data from file

In [157]:
filedata = np.genfromtxt('data.txt',delimiter=",")

In [158]:
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [160]:
filedata = filedata.astype('int32')

In [170]:
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean masking and advanced indexing

In [165]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [166]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [169]:
#You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [173]:
np.any(filedata>50,axis=0) #column wise

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [174]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [175]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [176]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [177]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [178]:
#negation of above code is
~((filedata>50)&(filedata<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

------------------------------****************--------------------------------