## Introduction to Tensorflow

In [1]:
#Tensorflow creates graphs for defined computations
#allows parts of the graphs to be executed
#Sessions are the executions of these parts of graphs

In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\saige\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


### Tensors

In [4]:
# Generalization of vectors and matrices to potentially higher dimensions
# Tensorflow represents tensors as n-dim arrays of base dt
# Each tensor has a dt and shape
# Each tensor represents partially defined computations that will eventually produce a value
# Tensorflow works by building a graph of tensorflow objects

#### Creating Tensors

In [5]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float64)
print(string,number,floating)
#these are rank 0 tensors

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


#### Rank/Degree of Tensors

In [6]:
rank1_tensor = tf.Variable(["Test","Ok","Tim"],tf.string)
rank2_tensor = tf.Variable([["Test","Ok"],["Test","yes"]],tf.string)
#tensors should be square matrices

In [7]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### Shape

In [8]:
rank2_tensor.shape

TensorShape([2, 2])

#### Changing shape

In [22]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2,[3,-1])
# -1 tells the tensor to infer the shape required to generate the tensor with 3 rows in this case
# the number of elements in the reshaped tensor must match the numer in the original

In [23]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors

In [24]:
# Variable
# Constant
# Placeholder
# SparseTensor

# variable tensor is the only one that is mutable rest all are immutable

### Evaluating Tensors

In [28]:
# For evaluating a tensor we need to create a session

# with tf.Session() as sess:
#     tensor.eval()